version: '3'
services:
  frontend:
    build: 
      context: ./frontend/php_webinterface
      dockerfile: Dockerfile
    container_name: frontend_php
    ports:
      - "80:80"
    volumes:
      - ./frontend/php_webinterface:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_started

  backend:
    build: ./backend/python
    container_name: dbdata_python
    depends_on:
      - mysql
      - mongodb

  mysql:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_USER: myuser
      MYSQL_DATABASE: mysql_queensmandb
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: Schikuta<3
    ports:
      - "3307:3306"
    volumes:
      - ./relational/mysql_scripts:/docker-entrypoint-initdb.d
      - mysqldb:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./non_relational/mongo_scripts/init:/docker-entrypoint-initdb.d
      - mongodata:/data/db

networks:
  backend_network:

volumes:
  mysqldb:
  mongodata:
