-- deletes all tables, procedures and triggers
DROP TABLE IF EXISTS TAKES_ON;
DROP TABLE IF EXISTS MISSIONLOG;
DROP TABLE IF EXISTS EXTERN_PARTNER;
DROP TABLE IF EXISTS SUBJECT;
DROP TABLE IF EXISTS ASSIGNED_TO;
DROP TABLE IF EXISTS BRANCH;
DROP TABLE IF EXISTS FACILITY_TYPE;
DROP TABLE IF EXISTS TOOL;
DROP TABLE IF EXISTS ANALYST;
DROP TABLE IF EXISTS AGENT;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS POST_CODE;

DROP PROCEDURE IF EXISTS AgentToolCnt;

-- Triggers are dropped automcally with their associated tables
